name: helm-template

eksClusterName: apps

ingress:
  enabled: false

deployment:
  enabled: true

service:
  type: ClusterIP
  port: 8080
  enabled: false

replicaCount: 1

autoscaling:
  enabled: false

image:
  repository: nginx
  tag: "1.14.2"
  pullPolicy: IfNotPresent
  port: 8080

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  path: /health/liveness
  inititalDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  path: /health/readiness
  inititalDelaySeconds: 30
  periodSeconds: 10

externalSecret:
  enabled: true

configmap:
  enabled: false
  data: {}

secret:
  enabled: false

externalSecrets:
  enabled: false

volumes:
  configmap:
    enabled: true
    appended:
      - name: configmap-name
  secret:
    enabled: false
    appended:
      - name: configmap-name

podAnnotations: {}
imagePullSecrets: []
serviceAccount: 
  create: false
  annotations: {}
podSecurityContext: {}

