{{- if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config
  labels:
    {{- include ".labels" . | nindent 4}}
  data:
    {{- toYaml .Values.configmap.data | nindent 6}}
{{- end }}