{{- if .Values.externalSecrets.enabled }}
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.name }}
spec:
  backendType: secretsManager
  dataFrom:
    - {{ .Values.externalSecrets.key }}
{{- end }}