{{- if .Values.externalSecrets.enabled }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.name}}
spec:
  backendType: secretManager
  data:
    - name: {{ .Values.name}}
      key: {{ .Values.externalSecrets.key }}
  dataFrom:
    - {{ .Values.externalSecrets.dataFrom }}
{{- end }}